<?php

declare(strict_types=1);

namespace Laratusk\Supervise\Services;

use Laratusk\Supervise\Enums\WorkerType;

class SupervisorCompiler
{
    /** @var list<string> */
    private const INTERNAL_KEYS = [
        'type', 'connection', 'queue', 'tries', 'max_time', 'sleep',
        'timeout', 'memory', 'backoff', 'max_jobs', 'force', 'rest', 'log',
    ];

    /**
     * @param  array<string, mixed>  $config
     */
    public function __construct(
        private readonly array $config,
        private readonly string $basePath,
    ) {}

    /**
     * Compile all worker and group .conf files to the given output path.
     *
     * @return list<string>
     */
    public function compile(string $outputPath): array
    {
        if (! is_dir($outputPath)) {
            mkdir($outputPath, 0755, true);
        }

        /** @var array<string, mixed> $defaults */
        $defaults = $this->config['defaults'] ?? [];

        /** @var array<string, array<string, mixed>> $workers */
        $workers = $this->config['workers'] ?? [];

        /** @var array<string, list<string>> $groups */
        $groups = $this->config['groups'] ?? [];

        $compiledFiles = [];

        foreach ($workers as $workerName => $workerConfig) {
            /** @var array<string, mixed> $merged */
            $merged = array_merge($defaults, $workerConfig);

            $content = $this->renderWorker($workerName, $merged);

            $filePath = $outputPath.DIRECTORY_SEPARATOR.$workerName.'.conf';
            file_put_contents($filePath, $content);
            $compiledFiles[] = $filePath;
        }

        foreach ($groups as $groupName => $workerNames) {
            $content = $this->renderGroup($groupName, $workerNames);

            $filePath = $outputPath.DIRECTORY_SEPARATOR.$groupName.'.conf';
            file_put_contents($filePath, $content);
            $compiledFiles[] = $filePath;
        }

        return $compiledFiles;
    }

    /**
     * @param  array<string, mixed>  $config
     */
    private function renderWorker(string $workerName, array $config): string
    {
        $type = WorkerType::from((string) $config['type']);

        if ($type === WorkerType::Horizon || $type === WorkerType::Reverb) {
            $config['process_name'] = '%(program_name)s';
        }

        if (! empty($config['log'])) {
            $config['stdout_logfile'] = $this->basePath.'/storage/logs/supervisor/'.$workerName.'.log';
        }

        $command = match ($type) {
            WorkerType::Horizon => "php {$this->basePath}/artisan horizon",
            WorkerType::Reverb => "php {$this->basePath}/artisan reverb:start",
            WorkerType::Queue => $this->buildQueueCommand($config),
        };

        $lines = [
            '; Auto-generated by laratusk/supervise — DO NOT EDIT MANUALLY',
            "[program:{$workerName}]",
            "command={$command}",
        ];

        foreach ($config as $key => $value) {
            if (in_array($key, self::INTERNAL_KEYS, true) || $value === null) {
                continue;
            }

            $lines[] = $key.'='.(is_bool($value) ? ($value ? 'true' : 'false') : (string) $value);
        }

        return implode("\n", $lines)."\n";
    }

    /**
     * @param  list<string>  $workers
     */
    private function renderGroup(string $groupName, array $workers): string
    {
        $lines = [
            '; Auto-generated by laratusk/supervise — DO NOT EDIT MANUALLY',
            "[group:{$groupName}]",
            'programs='.implode(',', $workers),
        ];

        return implode("\n", $lines)."\n";
    }

    /**
     * @param  array<string, mixed>  $config
     */
    private function buildQueueCommand(array $config): string
    {
        $cmd = "php {$this->basePath}/artisan queue:work";

        if (! empty($config['connection'])) {
            $cmd .= ' '.$config['connection'];
        }

        if (! empty($config['queue'])) {
            $queues = implode(',', (array) $config['queue']);
            $cmd .= " --queue={$queues}";
        }

        if (isset($config['sleep'])) {
            $cmd .= ' --sleep='.$config['sleep'];
        }

        if (isset($config['tries'])) {
            $cmd .= ' --tries='.$config['tries'];
        }

        if (isset($config['max_time'])) {
            $cmd .= ' --max-time='.$config['max_time'];
        }

        if (isset($config['timeout'])) {
            $cmd .= ' --timeout='.$config['timeout'];
        }

        if (isset($config['memory'])) {
            $cmd .= ' --memory='.$config['memory'];
        }

        if (isset($config['backoff'])) {
            $cmd .= ' --backoff='.$config['backoff'];
        }

        if (isset($config['max_jobs'])) {
            $cmd .= ' --max-jobs='.$config['max_jobs'];
        }

        if (isset($config['rest'])) {
            $cmd .= ' --rest='.$config['rest'];
        }

        if (! empty($config['force'])) {
            $cmd .= ' --force';
        }

        return $cmd;
    }
}
