<?php

declare(strict_types=1);

use Laratusk\Supervise\Services\SupervisorCompiler;

beforeEach(function (): void {
    $this->tmpDir = $this->makeTempDir();
    $this->basePath = $this->makeTempDir();
});

afterEach(function (): void {
    $this->removeDir($this->tmpDir);
    $this->removeDir($this->basePath);
});

it('compiles a worker config with custom command', function (): void {
    $config = [
        'defaults' => $this->defaultDirectives(),
        'workers' => [
            'horizon' => ['command' => 'php artisan horizon'],
        ],
        'groups' => [],
    ];

    $compiler = new SupervisorCompiler($config, $this->basePath);
    $files = $compiler->compile($this->tmpDir);

    expect($files)->toHaveCount(1);

    $content = file_get_contents($this->tmpDir.'/horizon.conf');
    expect($content)
        ->toContain('; Auto-generated by laratusk/supervise — DO NOT EDIT MANUALLY')
        ->toContain('[program:horizon]')
        ->toContain('command=php artisan horizon');
});

it('compiles a worker with command and supervisor overrides', function (): void {
    $config = [
        'defaults' => $this->defaultDirectives(),
        'workers' => [
            'emails' => [
                'command' => 'php artisan queue:work redis --queue=emails,notifications --tries=5 --max-time=7200',
                'numprocs' => 3,
            ],
        ],
        'groups' => [],
    ];

    $compiler = new SupervisorCompiler($config, $this->basePath);
    $files = $compiler->compile($this->tmpDir);

    expect($files)->toHaveCount(1);

    $content = file_get_contents($this->tmpDir.'/emails.conf');
    expect($content)
        ->toContain('[program:emails]')
        ->toContain('command=php artisan queue:work redis --queue=emails,notifications --tries=5 --max-time=7200')
        ->toContain('numprocs=3');
});

it('compiles a reverb worker config', function (): void {
    $config = [
        'defaults' => $this->defaultDirectives(),
        'workers' => [
            'reverb' => ['command' => 'php artisan reverb:start'],
        ],
        'groups' => [],
    ];

    $compiler = new SupervisorCompiler($config, $this->basePath);
    $files = $compiler->compile($this->tmpDir);

    expect($files)->toHaveCount(1);

    $content = file_get_contents($this->tmpDir.'/reverb.conf');
    expect($content)
        ->toContain('[program:reverb]')
        ->toContain('command=php artisan reverb:start');
});

it('merges worker config with defaults', function (): void {
    $defaults = $this->defaultDirectives();
    $defaults['numprocs'] = 1;
    $defaults['user'] = 'www-data';

    $config = [
        'defaults' => $defaults,
        'workers' => [
            'horizon' => [
                'command' => 'php artisan horizon',
                'numprocs' => 5,
            ],
        ],
        'groups' => [],
    ];

    $compiler = new SupervisorCompiler($config, $this->basePath);
    $compiler->compile($this->tmpDir);

    $content = file_get_contents($this->tmpDir.'/horizon.conf');
    expect($content)
        ->toContain('numprocs=5')   // worker override
        ->toContain('user=www-data'); // default
});

it('excludes null values from output', function (): void {
    $defaults = $this->defaultDirectives();
    $defaults['directory'] = null;
    $defaults['environment'] = null;

    $config = [
        'defaults' => $defaults,
        'workers' => [
            'horizon' => ['command' => 'php artisan horizon'],
        ],
        'groups' => [],
    ];

    $compiler = new SupervisorCompiler($config, $this->basePath);
    $compiler->compile($this->tmpDir);

    $content = file_get_contents($this->tmpDir.'/horizon.conf');
    expect($content)
        ->not->toContain('directory=')
        ->not->toContain('environment=');
});

it('renders booleans as true/false strings', function (): void {
    $defaults = $this->defaultDirectives();
    $defaults['autostart'] = true;
    $defaults['redirect_stderr'] = false;

    $config = [
        'defaults' => $defaults,
        'workers' => [
            'horizon' => ['command' => 'php artisan horizon'],
        ],
        'groups' => [],
    ];

    $compiler = new SupervisorCompiler($config, $this->basePath);
    $compiler->compile($this->tmpDir);

    $content = file_get_contents($this->tmpDir.'/horizon.conf');
    expect($content)
        ->toContain('autostart=true')
        ->toContain('redirect_stderr=false');
});

it('sets custom log path when log=true', function (): void {
    $config = [
        'defaults' => $this->defaultDirectives(),
        'workers' => [
            'horizon' => [
                'command' => 'php artisan horizon',
                'log' => true,
            ],
        ],
        'groups' => [],
    ];

    $compiler = new SupervisorCompiler($config, $this->basePath);
    $compiler->compile($this->tmpDir);

    $content = file_get_contents($this->tmpDir.'/horizon.conf');
    expect($content)
        ->toContain("stdout_logfile={$this->basePath}/storage/logs/supervisor/horizon.log");
});

it('compiles group config files', function (): void {
    $config = [
        'defaults' => $this->defaultDirectives(),
        'workers' => [
            'horizon' => ['command' => 'php artisan horizon'],
            'emails' => ['command' => 'php artisan queue:work --queue=emails'],
        ],
        'groups' => [
            'laravel-workers' => ['horizon', 'emails'],
        ],
    ];

    $compiler = new SupervisorCompiler($config, $this->basePath);
    $files = $compiler->compile($this->tmpDir);

    expect($files)->toHaveCount(3);
    expect(file_exists($this->tmpDir.'/laravel-workers.conf'))->toBeTrue();

    $content = file_get_contents($this->tmpDir.'/laravel-workers.conf');
    expect($content)
        ->toContain('; Auto-generated by laratusk/supervise — DO NOT EDIT MANUALLY')
        ->toContain('[group:laravel-workers]')
        ->toContain('programs=horizon,emails');
});

it('creates output directory if it does not exist', function (): void {
    $newDir = $this->tmpDir.'/new-subdir/conf.d';

    $config = [
        'defaults' => $this->defaultDirectives(),
        'workers' => [
            'horizon' => ['command' => 'php artisan horizon'],
        ],
        'groups' => [],
    ];

    $compiler = new SupervisorCompiler($config, $this->basePath);
    $compiler->compile($newDir);

    expect(is_dir($newDir))->toBeTrue();
    expect(file_exists($newDir.'/horizon.conf'))->toBeTrue();
});

it('is idempotent - overwrites existing files', function (): void {
    $config = [
        'defaults' => $this->defaultDirectives(),
        'workers' => [
            'horizon' => ['command' => 'php artisan horizon'],
        ],
        'groups' => [],
    ];

    $compiler = new SupervisorCompiler($config, $this->basePath);
    $compiler->compile($this->tmpDir);

    // Modify the file, then compile again
    file_put_contents($this->tmpDir.'/horizon.conf', 'MODIFIED');

    $compiler->compile($this->tmpDir);

    $content = file_get_contents($this->tmpDir.'/horizon.conf');
    expect($content)
        ->not->toBe('MODIFIED')
        ->toContain('[program:horizon]');
});

it('excludes internal keys from directive output', function (): void {
    $config = [
        'defaults' => $this->defaultDirectives(),
        'workers' => [
            'emails' => [
                'command' => 'php artisan queue:work --queue=emails',
                'log' => false,
            ],
        ],
        'groups' => [],
    ];

    $compiler = new SupervisorCompiler($config, $this->basePath);
    $compiler->compile($this->tmpDir);

    $content = file_get_contents($this->tmpDir.'/emails.conf');
    expect($content)
        ->not->toContain("\nlog=");
    // 'command' is rendered as the program command= line, not as a directive key
    expect($content)->toContain('command=php artisan queue:work --queue=emails');
});
